package psfp

import (
	"context"
	"regexp"
	"strings"
)

var reDetectCookie = regexp.MustCompile(`(?i)PrestaShop-[a-f0-9]{32}=`)

// Detect runs the high-confidence "is this PrestaShop?" signals, primary being
// the default static error500.html (present on every release, survives reskins
// and hardened .htaccess). Mirrors the prestashop-fast nuclei template.
// Returns as soon as the strong one-shot signal fires, else gathers fallbacks.
func (c *Client) Detect(ctx context.Context, base string) Detection {
	base = strings.TrimRight(base, "/")
	var sigs []string

	// PRIMARY - default error500.html meta (one-shot, every version)
	if r := c.fetch(ctx, base+"/error500.html", 1<<16); r != nil && r.status == 200 &&
		contains(r.body, "This store is powered by PrestaShop") {
		sigs = append(sigs, "error500.html")
		return Detection{Confirmed: true, Signals: sigs}
	}

	// FALLBACKS - webservice realm, session cookie, robots banner, JS global
	if r := c.fetch(ctx, base+"/api/", 1<<16); r != nil &&
		strings.Contains(r.header.Get("WWW-Authenticate"), "PrestaShop Webservice") {
		sigs = append(sigs, "webservice /api/ realm")
	}
	if r := c.fetch(ctx, base+"/", 1<<20); r != nil {
		if reDetectCookie.MatchString(strings.Join(r.header.Values("Set-Cookie"), " ")) {
			sigs = append(sigs, "PrestaShop-<md5> cookie")
		}
		if contains(r.body, "var prestashop =") || contains(r.body, "window.prestashop") {
			sigs = append(sigs, "window.prestashop JS global")
		}
	}
	if r := c.fetch(ctx, base+"/robots.txt", 1<<16); r != nil &&
		contains(r.body, "automatically generated by PrestaShop") {
		sigs = append(sigs, "robots.txt banner")
	}
	return Detection{Confirmed: len(sigs) > 0, Signals: sigs}
}
